### ISSUE TITLE
The extension doesn't work properly after install

### ISSUE THREAD

**Issue by skchrko** [pawelgrzybek/PinBuddy#7]
The main content window is empty.

Steps to reproduce:
- Install the extension
- Add API token.

Here's the console:
![screen shot 2018-10-16 at 13 23 01](https://user-images.githubusercontent.com/17317058/47010120-d5390580-d146-11e8-93ad-c286a3571e44.png)

Chrome is: Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by pawelgrzybek** [comment]
Thanks for reporting this bug. Just out of curiosity, do you have anything added to your Pinboard collection? The only case that I can think of when this one may happen is when API comes back with nor results (it is a bug and should be prevented of course).

**Comment by skchrko** [comment]
Yeah, I have several thousands of bookmarks (using Pinboard for quite a few years).

**Comment by pawelgrzybek** [comment]
Would you be able to provide me your token for debugging purpose (twitter dm or email)? I promise not to do anything nasty with your bookmarks. You can deactivate it and regenerate a new one straight after few my tests...

**Comment by pawelgrzybek** [comment]
Legend. Let me test it with your account and I will let you know when its done and deactivate this one. Thanks a lot again!

**Comment by pawelgrzybek** [comment]
I found an issue and unfortunately I have a bad news :(

PinBuddy caches posts for 5 minutes and then it requests the list of posts again. Your current data is 6.5mb of JSON data. Unfortunately `google.chrome.storage` is capable to store only 5MB, otherwise it returns an error.

https://developer.chrome.com/apps/storage#property-local

I may reconsider some better storage management in the future. Sorry about it, there is not much that I can do about it at the moment.

**Comment by skchrko** [comment]
I see, thanks!
